/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.annotation.processors;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
